site_name: gkaufman-dev
theme:
  name: material
  features:
    - content.tooltips
  favicon: images/assets/OIG1qnG6m.jpg
  logo: images/assets/OIG1qnG6m.jpg
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
nav:
  - index.md
  - about-me.md
plugins:
  - blog:
      blog_dir: .
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg